sudo: required
services:
 - docker

before_install:
  - docker build -t ptisma/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ptisma/react-test npm test

after_success:
  - docker build -t ptisma/multi-client ./client
  - docker build -t ptisma/multi-nginx ./nginx
  - docker build -t ptisma/multi-server ./server
  - docker build -t ptisma/multi-worker ./worker
  #log into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push images to docker hub
  - docker push ptisma/multi-client
  - docker push ptisma/multi-nginx
  - docker push ptisma/multi-server
  - docker push ptisma/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-671871959124'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY